version: '3'
services:
  db:
    image: mysql:5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9999:80"

  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www