api_platform:
  metadata_backward_compatibility_layer: false
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
    # paths: ["%kernel.project_dir%/config/api_platform/resources.yaml"]
  patch_formats:
    json: ["application/merge-patch+json"]
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    html: ["text/html"]
    multipart: ["multipart/form-data"]
  swagger:
    versions: [3]
